name: Continuous Deployment
on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    BACKEND_ECR_REPOSITORY: workshop-dvn-backend/production/backend
    FRONTEND_ECR_REPOSITORY: workshop-dvn-frontend/production/frontend
    IMAGE_TAG: ${{ github.sha }}

permissions:
    id-token: write
    contents: read

jobs:
    backend:
        name: Backend Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5.1.1
              with:
                  aws-region: us-east-1
                  role-to-assume: arn:aws:iam::874026451845:role/workshop-dvn-github-role

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push Docker image to Amazon ECR
              env:
                  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  REPOSITORY: ${{ env.BACKEND_ECR_REPOSITORY }}
              run: |
                  docker build -f ./dvn-apps/backend/YoutubeLiveApp/Dockerfile \
                   -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./dvn-apps/backend/YoutubeLiveApp
                  docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

            - name: Checkout GitOps
              uses: actions/checkout@v6
              with:
                repository: 'thalesvpsilva/workshop-dvn-gitops'
                token: ${{ secrets.PAT }}

                
            - name: Kustomize image
              env:
                  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  REPOSITORY: ${{ env.BACKEND_ECR_REPOSITORY }}
              run: |
                  kustomize edit set image $REGISTRY/$REPOSITORY=$REGISTRY/$REPOSITORY:$IMAGE_TAG
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add ./kustomization.yml
                  git commit -m "[BOT] Update backend image to $REGISTRY/$REPOSITORY:$IMAGE_TAG"
                  git push

            